= Technical Documentation: Set up authenticate feature

== Author(s)

* Stijn Taelemans

== References

* https://www.wrike.com/open.htm?id=674718417[Wrike task]
* Branch: `feat/599439372-set-up-authenticate-feature`
* Project:
https://github.com/digita-ai/nde-erfgoedinstellingen[nde-erfgoed-manage]

== Introduction

=== Overview

This document is about the setup of the authentication feature. Heritage institutions should be able to authenticate to the heritage management application with their WebIDs. 

=== Out of scope

Any visual components or implementations of services for the authentication feature are to be made at a later time.

=== Assumptions

The initial project setup is complete.

== Solution

=== Suggested or proposed solution

==== Authentication Feature

Under 'lib/features', create new 'authenticate' directory. In here, create the following files:

* authenticate.machine.ts
* authenticate.context.ts
* authenticate.actions.ts
* authenticate.events.ts

==== Machine

Create in 'lib/features/authenticate/authenticate.machine.ts'

todo describe machine


==== Context

Create in 'lib/features/authenticate/authenticate.context.ts'

todo


==== Actions and Events

Create following actions in 'lib/features/authenticate/authenticate.actions.ts'

Create following events in 'lib/features/authenticate/authenticate.events.ts'

todo describe actions, events


==== Components

===== AuthenticationRootComponent

The finished component should look like this:

image::authenticate-root.svg[AuthenticationRootComponent]

Generate under 'lib/features/authenticate/root/authenticate-root.component.ts'

Set up an empty Web Component for now. This component will be fleshed out when the other authentication-related components are made.


==== Configuring the App Machine

The Authenticate Machine should be registered in the App Machine.

todo finish this
