= Technical Documentation: Create authenticate login page

== Author(s)

* Stijn Taelemans

== References


* https://www.wrike.com/open.htm?id=682525025[Wrike task]
* Branch: `feat/create-content-header-component`
* Projects: https://github.com/digita-ai/nde-erfgoedinstellingen[nde-erfgoed-components]


== Introduction

=== Overview

This document is about the creation of a reusable content header component.


=== Assumptions

All components are to be made in the '@digita-ai/nde-erfgoed-components' package.


== Solution

=== Suggested or proposed solution

==== ContentHeaderComponent 

The finished component should look like this:

image::../../assets/collections/content-header.svg[ContentHeaderComponent]

Generate in '@digita-ai/nde-erfgoed-components' package under 'lib/common/header/content-header.component.ts', with tag `<nde-content-header>`

Export the component in 'lib/index.ts'.

To preview the component while developing: register the component in 'lib/demo.ts', then add the component's tag to the 'index.html' file in the 'lib' directory. Running `npm run start:watch` in the 'nde-erfgoed-components' package will serve the 'index.html' file you just edited.
