= Collecties
:description: Een gebruikershandleiding voor het beheren van collecties in Solid CBS.
:sectanchors:
:url-repo: https://github.com/digita-ai/nde-erfgoedinstellingen
:imagesdir: ../images

== Hoe beheer ik de collecties van mijn erfgoedinstelling?

Dit document toont je hoe je de collecties van je erfgoedinstelling beheert in het Solid Collectiebeheersysteem. 


=== Vereisten
Om collecties te kunnen beheren, moet je zijn ingelogd op het Collectiebeheersysteem van jouw erfgoedinstelling. Meer uitleg over inloggen vind je op * xref:authenticeer.adoc[authenticeer].

=== Maak een nieuwe collectie aan
Klik links in de primaire navigatiebalk op het plusje, naast 'Collecties'. Er wordt nu een nieuwe collectie geopend.

=== Pas de naam en onderschrift van de collectie aan
Zorg dat je de gewenste collectie in de primaire naviagtiebalk hebt geselecteerd. Klik op de naam van de collectie, bovenaan de pagina. Je kan nu de naam en het onderschrift aanpassen. Wanneer je klaar bent, druk je rechts op het 'opslaan' icoontje om op te slaan of op het kruisje om te annuleren. 

=== Verwijder de collectie
Selecteer de collectie die je wilt verwijderen in de primaire naviagtiebalk. Druk in de rechterbovenhoek op het vuilbak-icoontje om de volledige collectie te verwijderen. 


