= Hoe beheer ik de collecties van mijn erfgoedinstelling?
:description: Een gebruikershandleiding voor het beheren van collecties in Solid CRS.
:sectanchors:
:url-repo: https://github.com/netwerk-digitaal-erfgoed/solid-crs
:imagesdir: ../images
:sectnums:


Dit document toont je hoe je de collecties van je erfgoedinstelling beheert in het Solid Collectieregistratiesysteem. 


=== Vereisten
Om collecties te kunnen beheren, moet je zijn ingelogd op het Collectiebeheersysteem van jouw erfgoedinstelling. Meer uitleg over inloggen vind je op xref:authenticeer.adoc[authenticeer].

=== Maak een nieuwe collectie aan
Klik links in de primaire navigatiebalk op het plusje, naast 'Collecties'. Er wordt nu een nieuwe collectie geopend.

=== Pas de naam en onderschrift van de collectie aan
Zorg dat je de gewenste collectie in de primaire naviagtiebalk hebt geselecteerd. Klik op de naam van de collectie, bovenaan de pagina. Je kan nu de naam en het onderschrift aanpassen. Wanneer je klaar bent, druk je rechts op het 'opslaan' icoontje of enter om op te slaan. Om te annuleren, druk je op het kruisje. 

=== Verwijder de collectie
Selecteer de collectie die je wilt verwijderen in de primaire naviagtiebalk. Druk in de rechterbovenhoek op het vuilbak-icoontje om de volledige collectie te verwijderen. 

=== Voeg een object toe aan de collectie
Net zoals je collecties kan toevoegen met het plus-icoontje in de linker navigatiebalk, kan je objecten toevoegen aan een collectie met het plus-icoontje in de rechterbovenhoek van de collectiepagina. Wanneer je op het plus-icoontje rechtsboven klikt zal er een nieuw object aangemaakt worden in de collectie, waarna je doorgestuurd wordt naar de objectpagina. Hoe je een object aanpast lees je in xref:objecten.adoc[objecten].


==== Biedt dit geen antwoord op jouw vraag? Dan vind je het mogelijks wel in een van de volgende pagina's: 
* xref:authenticeer.adoc[Authenticatie]
* xref:objecten.adoc[Objecten]
* xref:search.adoc[Zoeken]
* xref:termennetwerk.adoc[Termennetwerk]
* xref:presentatiemodule.adoc[Presentatiemodule]
