= Hoe beheer ik de objecten van mijn erfgoedinstelling?
:description: Een gebruikershandleiding voor het beheren van objecten in Solid CRS.
:sectanchors:
:url-repo: https://github.com/netwerk-digitaal-erfgoed/solid-crs
:imagesdir: ../images

Dit document toont je hoe je de objecten van je erfgoedinstelling beheert in het Solid Collectieregistratiesysteem. 


=== Vereisten
Om objecten te beheren, moet je aangemeld zijn op het Collectieregistratiesysteem. Meer uitleg over aanmelden vind je op xref:authenticeer.adoc[de authenticeer pagina]. 

=== Maak een nieuw object aan
Kies de collectie waaraan je het object wilt toewijzen door de gewenste collectie te selecteren in de primaire navigatie (links). Wanneer de collectie nog geen objecten bevat, kan je in het midden van het scherm op de knop 'object aanmaken' klikken. Wanneer de collectie wel reeds objecten bevat, kan je een object toevoegen door rechtsboven op het plusje te klikken. Je wordt nu doorgestuurd naar de objectdetailpagina. 

=== Pas de titel en onderschrift van het object aan
Klik op de titel van het object, bovenaan de pagina. Je kan nu de naam en het onderschrift aanpassen. Wanneer je klaar bent, druk je rechts op het 'opslaan' icoontje of enter om op te slaan. Om te annuleren, druk je op het kruisje. 

=== Verwijder een object
Ga naar het object dat je wilt verwijderen. Druk in de rechterbovenhoek op het vuilbak-icoontje. Het object is nu verwijderd.

=== Sla wijzingingen op
Klik na het uitvoeren van wijzigingen op het 'opslaan'-icoontje in de rechterbovenhoek.

=== Details van een object aanpassen
In de secundaire navigatiebalk kan je het gewenste onderdeel aanklikken waarvan je de details wilt aanpassen. Je kan het onderdeel ook vinden door te scrollen, de navigatie zal zich dan mee aanpassen. Vergeet niet om de wijzigingen op te slaan.
Hieronder worden de aan te passen velden per onderdeel besproken.

. Beeldmateriaal
* Bestand: +
Typ of plak de URL die naar de afbeelding verwijst.
* Licentie: +
Kies de correcte licentie uit de lijst.

. Identificatie
* Objectnummer: +
Typ de unieke code waarmee het object kan worden geïdentificeerd.
* Type: +
* Objectnaam: +
* Titel: +
Vul de titel in van het object. De titel bovenaan de pagina zal automatisch mee worden aangepast wanneer je dit veld aanpast. Omgekeerd zal dit veld ook aangepast worden wanneer je de titel bovenaan de pagina wijzigt. 
* Korte beschrijving: +
Geef een korte en bondige beschrijving van het object. 
* Collectie: +
Indien je het object aan een andere collectie wilt toewijzen dan waar het object werd in gemaakt, kan je dit hier doen door de gewenste collectie te selecteren uit de lijst.

. Vervaardiging
* Vervaardiger: +
Klik rechts op de knop om naar de pagina van het xref:termennetwerk.adoc[termennetwerk] te gaan. Zoek op naam van de vervaardiger in één of meerdere thesauri. Selecteer de gewenste term en klik op 'bevestig'. 
* Plaats: + 
Klik rechts op de knop naar het xref:termennetwerk.adoc[termennetwerk]. Zoek de plaatsnaam in één of meerdere thesauri. Selecteer de gewenste term en klik op 'bevestig'. 
* Materiaal: + 
Klik rechts op de knop naar het xref:termennetwerk.adoc[termennetwerk]. Zoek het materiaal in één of meerdere thesauri. Selecteer de gewenste term en klik op 'bevestig'. 
* Datum: + 
Geef de datum van vervaardiging in als YYYY-MM-DD, waarbij YYYY staat voor jaar, MM staat voor maand en DD staat voor dag. Het is echter ook mogelijk om enkel een jaartal of enkel een jaartal en maand in te geven wanneer de exacte datum niet geweten is.

. Voorstelling
* Onderwerp: +
Klik rechts op de knop naar het xref:termennetwerk.adoc[termennetwerk]. Zoek het onderwerp in één of meerdere thesauri. Selecteer de gewenste term en klik op 'bevestig'. 
* Locatie: +
Klik rechts op de knop naar het xref:termennetwerk.adoc[termennetwerk]. Zoek de locatie in één of meerdere thesauri. Selecteer de gewenste term en klik op 'bevestig'. 
* Persoon: +
Klik rechts op de knop naar het xref:termennetwerk.adoc[termennetwerk]. Zoek de persoon in één of meerdere thesauri. Selecteer de gewenste term en klik op 'bevestig'. 
* Organisatie: +
Klik rechts op de knop naar het xref:termennetwerk.adoc[termennetwerk]. Zoek de organisatie in één of meerdere thesauri. Selecteer de gewenste term en klik op 'bevestig'. 
* Gebeurtenis: +
Klik rechts op de knop naar het xref:termennetwerk.adoc[termennetwerk]. Zoek de gebeurtenis in één of meerdere thesauri. Selecteer de gewenste term en klik op 'bevestig'. 

. Afmetingen: +
Vul voor de hoogte, breedte, diepte en het gewicht het cijfer in en duid in de lijst aan in welke maateenheid van toepassing is.








:sectnums!:
==== Biedt dit geen antwoord op jouw vraag? Dan vind je het mogelijks wel in een van de volgende pagina's: 

* xref:authenticeer.adoc[Authenticatie]
* xref:search.adoc[Zoeken]
* xref:collecties.adoc[Collecties]
