= Solid voor kleine erfgoedinstellingen
ifdef::env-github,env-browser[:relfilesuffix: .adoc]

Opzet van een collectiebeheersysteem voor digitale objecten van kleine erfgoedinstellingen. Het systeem bestaat uit drie lagen: onboarding, beheer en presentatie. Beheerders kunnen collecties en objecten toevoegen, bezoekers kunnen deze browsen op de publieke website.Het systeem is beperkt tot collecties van beeldmateriaal en heeft beperkte functies voor gebruikers. 

* xref:docs/modules/ROOT/nav.adoc[Project documentation]
* xref:docs/modules/manual/nav.adoc[User manual]

== Run locally

When running the app locally for the first time, start by installing its dependencies. You can do so by executing the following command in the root of the cloned repository.

[source,bash]
----
$ npm run bootstrap:no-ci
----

Once the dependencies have installed, you can start the app by executing the following command.

[source,bash]
----
$ npm run start
----

The `start` command automatically builds the necessary dependencies before starting the application. However, you can also build the app and its dependencies separately from the `start` command as follows.

[source,bash]
----
$ npm run build
----

== Run with Docker

You can run the application by using docker. To use the latest published version, run the following command.

[source,bash]
----
$ docker run -p 3002:3002 ghcr.io/digita-ai/nde-erfgoed-manage:latest
----

Alternatively, you can build and run an image locally.

[source,bash]
----
$ docker build --build-arg NPM_TOKEN=$NPM_TOKEN -t cbs:local ./packages/nde-erfgoed-manage/
$ docker run -p 3002:3002 cbs:local
----
