= Technical Documentation: Set up authenticate feature

== Author(s)

* Stijn Taelemans


== References

* https://www.wrike.com/open.htm?id=674718417[Wrike task]
* Branch: `feat/599439372-set-up-authenticate-feature`
* Project: https://github.com/digita-ai/nde-erfgoedinstellingen[nde-erfgoed-manage]

== Introduction

=== Overview

This document is about the setup of the authentication feature. Heritage institutions should be able to authenticate to the heritage management application with their WebIDs. 


=== Out of scope

Any visual components or implementations of services for the authentication feature are to be made at a later time.


=== Assumptions
The initial project setup is complete.


== Solution

=== Suggested or proposed solution

==== Authentication Feature

Under 'lib/features', create new 'authenticate' directory. In here, create the following files:

* authenticate.machine.ts
* authenticate.states.ts
* authenticate.context.ts
* authenticate.actions.ts
* authenticate.events.ts


==== Authenticate Machine & States

Create `authenticateConfig`, `AuthenticateActors` in 'lib/features/authenticate/authenticate.machine.ts'.

Create `AuthenticateStates`, `AuthenticateState` and `AuthenticateSchema` in 'lib/features/authenticate/authenticate.states.ts'.

See https://xstate.js.org/docs/guides/machines.html#configuration[XState Machines documentation].

The `authenticateConfig` has three possible states: 

* `AuthenticateStates.UNAUTHENTICATED` (initial)
* `AuthenticateStates.AUTHENTICATING`
* `AuthenticateStates.AUTHENTICATED`

image::../images/authenticate/authenticate-machine-state-chart.svg[AuthenticateMachine State Chart]

The `AuthenticateStates.UNAUTHENTICATED` state is the initial state of the machine. From here, it can transition to the `AuthenticateStates.AUTHENTICATING` state when the `AuthenticateEvents.CLICKED_LOGIN` event is called. The machine should be in the `AuthenticateStates.AUTHENTICATING` state from the moment the button is clicked. The app should transition to `AuthenticateStates.AUTHENTICATED` using the `AuthenticateEvents.LOGIN_SUCCESS` event when the `handleIncomingRedirect()` function is called and its return value contains a `isLoggedIn` attribute equal to `true`. Should `isLoggedIn` be `false`, a `AuthenticateEvents.LOGIN_ERROR` event should be dispatched and the machine should return to its initial state. After `AuthenticateEvents.LOGIN_SUCCESS`, we reach the `AuthenticateStates.AUTHENTICATED` state. From this state, the machine can go back to the `AuthenticateStates.UNAUTHENTICATED` state when a `AuthenticateEvents.CLICKED_LOGOUT` action is fired.

Take a look at the existing `CollectionsState(s)`, `CollectionsSchema`, `CollectionsActors` ('lib/features/collections/collections.states.ts') and `collectionsMachine` ('lib/features/collections/collections.machine.ts') for inspiration on how to set up an XState machine.


==== AuthenticateContext

Create in 'lib/features/authenticate/authenticate.context.ts'

The context of the `AuthenticateMachine` is relatively simple. It contains the session to be used by the Inrupt auhtentication client. 
[source, js]
----
{
  session: Session,
}
----

The initial value of `session` should be `new Session()`.

==== Events

Create following events in 'lib/features/authenticate/authenticate.events.ts'

Take a look at https://github.com/digita-ai/nde-erfgoedinstellingen/blob/develop/packages/nde-erfgoed-manage/lib/features/collections/collections.events.ts[collections.events.ts] and https://github.com/digita-ai/nde-erfgoedinstellingen/blob/develop/packages/nde-erfgoed-manage/lib/features/collections/collections.actions.ts[collections.actions.ts].

[options="header"]
|======================================
| Event 	| Payload

| `AuthenticateEvents.CLICKED_LOGIN`
| `webId: string`

| `AuthenticateEvents.LOGIN_SUCCESS`
| No payload

| `AuthenticateEvents.LOGIN_ERROR`
| `msg: string`

| `AuthenticateEvents.CLICKED_LOGOUT`
| No payload

|======================================


==== Actions

Create following actions in 'lib/features/authenticate/authenticate.actions.ts'

[options="header"]
|======================================
| Action 	| Description

| `setSession(session: Session)`
| Should set `context.session` to `session`.

| `deleteSession(session: Session)`
| Should set `context.session` to its initial value.

|======================================


==== Services

Create following service functions in 'lib/features/authenticate/authenticate.services.ts'

Take a look at 'lib/features/collections/collections.services.ts' for inspiration. These functions will be called by the machine state's `invoke` attribute.

[options="header"]

|======================================
| Service function 	| Description

| `login(webId: string)`
| Should call the `context.session.login()` function.

| `logout()`
| Should call the `context.session.logout()` function.

|======================================


===== SolidService

Create in '@digita-ai/nde-erfgoed-core' package under 'lib/solid/solid.service.ts'.

This service handles everything Solid-related, from authenticating to fetching data. It relies mostly on Inrupt's open source SDKs.  Take a look at the https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/restore-session-browser-refresh/#enable-session-restore[authentication in a browser environment example].

For now, implement the `getIssuer()` function.

`getIssuer(webId: string): Observable<string>` will be used for validating the input field of the `AuthenticateLoginPageComponent`.  
Test URL validity with `new URL()`. Retrieve the OIDC issuer using `this.getIssuer()`. Fetching '<issuer_url>/.well-known/openid-configuration' should return a JSON object containing a `solid_oidc_supported` key.

The `getIssuer(webId: string): Observable<string>` should query a user's profile for the `oidcIssuer` triple and return its value.

==== Components

===== AuthenticateRootComponent

Generate under 'lib/features/authenticate/authenticate-root.component.ts'

Set up an empty Web Component for now. This component will be fleshed out when the other authentication-related components are made. Its purpose is to house the `AuthenticateLoginPageComponent`, to be made later.


==== Configuring the App Machine

The `authenticateConfig` should be configured in the `appState` as a https://xstate.js.org/docs/guides/parallel.html#parallel-state-nodes[parallel state node]. 
