= Technical Documentation: Create collection overview page

== Author(s)

* Stijn Taelemans

== References


* https://www.wrike.com/open.htm?id=682525025[Wrike task]
* Branch: `feat/create-content-header-component`
* Projects: https://github.com/digita-ai/nde-erfgoedinstellingen[nde-erfgoed-components]


== Introduction

=== Overview

This document is about the creation of the overview page for a single collection.


=== Assumptions

The collection feature's basic implementation is finished.

The shared components needed for this spec are created. 

== Solution

=== Suggested or proposed solution

==== Collection 

==== CollectionRootComponent

The finished component should look like this:

image::../../images/collections/collection-root.svg[CollectionRootComponent]

Create in '@digita-ai/nde-erfgoed-manage' package under 'lib/collections/pages/collection-root.component'. (might already exist)

The component contains a `ContentHeaderComponent` at the top, followed by a https://css-tricks.com/snippets/css/complete-guide-grid/[grid] of `ObjectCardComponents`. The header contains the title and description of the current component. These should be made so that, when the edit action icon is clicked, they can be edited with input fields. The value of these input fields can be saved by clicked the save action on the right, which replaces the edit icon. When editing (`CollectionsState.EDITING`), a new cancel icon is shown as well, to leave the editing state. The other two action icons in the header, create and delete, should fire the `CollectionEvents.CLICKED_CREATE_OBJECT` and `CollectionEvents.CLICKED_DELETE` events, respectively.

Every `CollectionObject` in the current `Collection` should be displayed using a grid of `ObjectCardComponents`. Clicking these should not do anything, yet. Try to adjust the grid dimensions based on window width. With default view widths, three cards should be displayed next to eachother.

image::../../images/collections/collection-root-no-objects.svg[CollectionRootComponent without CollectionObjects]

If the component does not contain any `CollectionObjects`, the page should display a large icon. (see image)  
The svg for this icon can be found on Figma, export it and add it to the theme package. 


==== AppRootComponent

The finished component should look like this:

image::../../images/collections/app-root.svg[AppRootComponent]

Exists in '@digita-ai/nde-erfgoed-manage' package under 'lib/'.

The component consists of the sidebar component, with a `ContentHeaderComponent`, an input field (`FormElementComponent`) and all found collections as `SidebarListItemComponents` in a `SidebarListComponent`. A detailed view of the currently selected collection (`CollectionRootComponent`) is visible on the right. (using a `CollectionRootComponent`)

Some actions need to happen when certain items are clicked within the sidebar. Clicking the logout icon in the content header of the sidebar should fire the `AppEvents.LOGGING_OUT` event to the parent of the `CollectionsMachine`. When the search input is submitted, the machine should catch the submitted event and filter the collections in its context based on the input. When one of the list items is clicked, the `CollectionEvents.SELECTED_COLLECTION` should be fired, with the `Collection` in its payload. Event fired from the `CollectionRootComponent` should not be handled in this component.
