= Scope
:description: A description of the scope used in the Actueel Inkomen PoC project.
:sectanchors:
:url-repo: https://github.com/digita-ai/aiv-actueel-inkomen
:page-tags: aiv-actueel-inkomen 
:imagesdir: ../images

== Definitions

[options="header",]
|===
|Term                       | Definition
|`Gebruiker`                | Persoon die het `collectiebeheersysteem` gebruikt als `beheerder` of `bezoeker`.
|`Collectiebeheersysteem`   | 
|`Beheerder`                | `Gebruiker` die de `Pod` en daarbij horende collecties en objecten van de ergfoedinstelling beheert.
|`Bezoeker`                 | `Gebruiker` die de publieke website van NDE bezoekt.
|`Pod`                      | Container waarin data van een kleine ergfoedinstelling is opgeslaan.
|`Digitaal object`          | Digitale representatie van een erfgoedobject.
|`Digita Connect`           | Middleware application to easily read from- and write to pods.

|===

== Assumptions

* Het collectiebeheersysteem is een ‘minimum viable product’ (MVP).
* Het collectiebeheersysteem is bestemd voor ‘behapbare collecties’​.
* Het collectiebeheersysteem heeft beperkte rollen en rechten voor gebruikers​.
* Het collectiebeheersysteem is bestemd voor één soort erfgoedobject: beeldmateriaal​.
* Het collectiebeheersysteem legt beperkte, vaststaande informatie vast​.
* Het collectiebeheersysteem is Nederlandstalig​, evt de user interface in Eng, Fr.
* Het collectiebeheersysteem publiceert erfgoedinformatie als Linked Data​.
* Het collectiebeheersysteem publiceert erfgoedinformatie via een publiekswebsite​. 



== Functional requirements

[arabic]
. Als `bezoeker` wil ik erfgoedobjecten kunnen terugvinden in het collectiebeheersysteem door te browsen.
. Als `bezoeker` wil ik per instelling de collectie kunnen bekijken.
. Als `beheerder` wil ik een account aanmaken in het `collectiebeheersysteem` (onboarding).
. Als `beheerder` wil ik een collectie aanmaken in het `collectiebeheersysteem`.
. Als `beheerder` wil ik nieuwe items toevoegen aan de pod van mijn instelling.
. Als 


As a `citizen`, I want to log in at Flemish Government.
. As a `citizen`, I want to create a dossier that contains my application for a social contribution.
. As `automatic advice`, I want to get a list of employments of a citizen.
. As `automatic advice`, I want to register the citizen at Digita Connect.
. As `automatic advice`, I want to requests the payslips for a citizen for a specific time period from Digita Connect.
. As `Digita Connect`, I want to request the payslips for a citizen for a specific time period from the citizen's pod.
. As a `citizen`, I want to get advice on my dossier that contains my application for a social contribution.
. As a `citizen`, I want to grant access to my `pod` by authenticating so that I can re-use my salary information of the past month.

== Non-functional requirements

[arabic]
. The demo environment will be described as a Docker Compose file.
. The performance of the software artefacts needs to be adequate for a
good user experience, but does not need to work at scale.
. The quality of the software artefacts needs to be adequate for testing
purposes, but does not need to be of production quality.
. The software artefacts will be built by using technologies of Digita’s
choice, and may include proprietary software development kits.
. The software artefacts will be tested on a limited set of modern web
browsers, such as Chrome and Firefox.
. The software artefacts will be designed for a single resolution.

== Out of scope

[arabic]
. Het verbeteren of doorontwikkelen van een Solid-opslagserver of implementatie van andere gedistribueerde technieken zoals IPFS of blockchain.
. Technische aansluiting op andere NDE-voorzieningen zoals het Termennetwerk en de registerfunctie.